export const Roboto = {
  bold: 'Roboto-Bold',
  thin: 'Roboto-Thin',
  black: 'Roboto-Black',
  light: 'Roboto-Light',
  italic: 'Roboto-Italic',
  medium: 'Roboto-Medium',
  regular: 'Roboto-Regular',
  condensed: 'Roboto-Condensed',
  thinItalic: 'Roboto-ThinItalic',
  boldItalic: 'Roboto-BoldItalic',
  blackItalic: 'Roboto-BlackItalic',
  lightItalic: 'Roboto-LightItalic',
  mediumItalic: 'Roboto-MediumItalic',
  specimenBook: 'Roboto_Specimen_Book',
  boldCondensed: 'Roboto-BoldCondensed',
  condensedItalic: 'Roboto-CondensedItalic',
  boldCondensedItalic: 'Roboto-BoldCondensedItalic',
};
