export const images = {
  pin: require('../Assets/icons/pin.png'),
  menu: require('../Assets/icons/menu.png'),
  logo: require('../Assets/images/Logo.png'),
  phone: require('../Assets/icons/phone.png'),
  theme: require('../Assets/images/theme.png'),
  camera: require('../Assets/icons/camera.png'),
  Search: require('../Assets/icons/Search.png'),
  shape1: require('../Assets/images/shape1.png'),
  shape2: require('../Assets/images/shape2.png'),
  shape3: require('../Assets/images/shape3.png'),
  shape4: require('../Assets/images/shape4.png'),
  shape5: require('../Assets/images/shape5.png'),
  downArrow: require('../Assets/icons/down.png'),
  emoji: require('../Assets/icons/emoji.png'),
  payment: require('../Assets/icons/payment.png'),
  profile1: require('../Assets/images/profile1.png'),
  profile2: require('../Assets/images/profile2.png'),
  profile3: require('../Assets/images/profile3.png'),
  profile4: require('../Assets/images/profile4.png'),
  profile5: require('../Assets/images/profile5.png'),
  profile6: require('../Assets/images/profile6.png'),
  backArrow: require('../Assets/icons/backArrow.png'),
  videoCall: require('../Assets/icons/videoCall.png'),
  mic_white: require('../Assets/icons/mic_white.png'),
  send: require('../Assets/icons/send_Icon.png'),
  whatsAppBG1: require('../Assets/images/whatsAppBG1.png'),
};
